# Generated by Django 5.0.6 on 2024-05-29 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_plat_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plat",
            options={
                "permissions": [
                    ("publish_plat", "can publish plat"),
                    ("sell_plat", "can sell plat"),
                    ("rate_plat", "ca rate plat"),
                ]
            },
        ),
    ]
